#!/usr/bin/env bash
# Dig info from domains

dig_info()
{
    row=$(dig "$2" | grep -A1 'ANSWER SECTION:' | tail -n+2)
    row="$1 $row"
    echo "$row" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ -n "$2" ]
then
    dig_info "$2" "$2.$1"
elif [ -n "$1" ]
then
    dig_info "www" "www.$1"
    dig_info "lb-01" "lb-01.$1"
    dig_info "web-01" "web-01.$1"
    dig_info "web-02" "web-02.$1"   
fi
