#!/usr/bin/env bash
# installs nginx

apt-get -y update
apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
redirection="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "37i\ $redirection" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
