#!/usr/bin/env bash
# sets 404 html error

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
error_pag="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $error_pag" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
