#!/usr/bin/env bash
# Get nginx listen on port 80.- Do symlinks sites-available to sites-enabled.
# sites-available came configured to listen to 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
