#!/usr/bin/env bash
# This script that loops from 1 to 10 and
# displays messages according to the number
i=0

while [ $i -lt 10 ]; do
	((i++))
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
done
