#!/usr/bin/env bash
#Prints 1-20 to stdout using a while loop.
#Prints something unique on the 4th, 9th and 17th iterations
i=0
while [ $i -lt 20 ]; do
	(( i++ ))
	echo $i
	case $i in
		4)  echo "bad luck from China";;
		9)  echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
done
